project: 
  type: website
  render: 
    - "*.qmd"
    - "!R/"

website: 
  page-navigation: true
  title: "Adrift in the California Current" 
  site-url: "https://nmfs-opensci.github.io/NOAA-quarto-simple" 
  repo-url: "https://sael-swfsc.github.io/Adrift/"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://tethys.pnnl.gov/sites/default/files/styles/captioned_400xauto/public/taxonomy-images/Screenshot%202022-09-13%20150029.jpg?itok=X_okXi_I"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://sael-swfsc.github.io/Adrift/
        text: "Adrift Website"
      - icon: github
        href: https://github.com/SAEL-SWFSC/Adrift
        text: "Adrift Repository"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - section: "Background"
        contents:
        - href: content/background.qmd
          text: Background
        - href: content/objectives.qmd
          text: Objectives
        - href: content/studyArea.qmd
          text: Study Area
        - href: content/driftingRecorders.qmd
          text: Drifting Recorders
      - section: "Marine Mammal Detections"
        contents:
        - href: content/detections.qmd
          text: Summary
        - href: content/sperm.qmd
          text: Sperm Whales
        - href: content/beaked.qmd
          text: Beaked Whales
        - href: content/dolphins.qmd
          text: Dolphins
        - href: content/nbhf.qmd
          text: NBHF
        - href: content/blue.qmd
          text: Blue Whales
        - href: content/humpback.qmd
          text: Humpback Whales
        - href: content/brydesSei.qmd
          text: Brydes/Sei Whales
        - href: content/gray.qmd
          text: Gray Whales
        - href: content/minke.qmd
          text: Minke Whales
      - section: "Soundscape"
        contents:
        - href: content/soundscape.qmd
          text: Soundscape
        - href: content/shipNoise.qmd
          text: Ship Noise
        - href: content/contributorsSS.qmd
          text: Contributors to Soundscape
      - section: content/dataSharing.qmd
        contents:
        - href: content/detections.qmd
          text:
      - section: content/outreach.qmd
        text: Outreach
        contents:
        - content/sdusd.qmd
        - content/dataNuggets.qmd
        - content/zooniverse.qmd
        - content/soundBytes.qmd
        - content/soundCloud.qmd
      - href: content/dataSharing.qmd 
        text: Data Sharing
      - href: content/outreach.qmd
        text: Outreach
      - section: "Summary"
        contents:
        - href: content/summary.qmd
          text: Summary of Results
        - href: content/recommendations.qmd
          text: Recommendations
      # - section: "Appendices"
      #   contents:
      #   - href: content/expandedData.qmd #
      #     text: Expanded Datasets
      #   - href: content/spermDemographics.qmd
      #     text: Sperm Whale Demographics
      #   - href: content/beakedDensity.qmd
      #     text: Beaked Whale Density Estimation
      #   - href: content/nbhfClassification.qmd
      #     text: NBHF Species Classification
      #   - href: content/finAI.qmd
      #     text: Fin Whale AI
      #   - href: content/habitatModels.qmd
      #     text: Modeling Habitat Use
      #   - href: content/spatialNoise.qmd
      #     text: Spatial Variation in Noise

          
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    code-fold: true


filters:
  - include-files.lua
  - quarto

  
