---
title: Summary
---

The greater Adrift in the California Current survey was intended to provide additional baseline data on marine mammals and the marine soundscape to inform management of offshore renewable resource development in the California Current. The Adrift-ACCESS collaboration between NOAA Fisheries and the Greater Farallones and Cordell Bank National Marine Sanctuaries provided an opportunity to deploy drifting recorders in and near the sanctuary waters offshore San Francisco Bay. Specific objectives of the Adrift-ACCESS Survey included assessing the viability and value of deploying drifting recorders during ACCESS Surveys, identifying marine mammal species within the sanctuaries, and providing additional information on the detection of blue and fin whales within and offshore the sanctuaries. 

***Determine the viability and value of coordinated drifting recorder PAM monitoring during ACCESS Surveys*** 

Drifting acoustic recorders were successfully deployed and retrieved during ACCESS Surveys by shipboard personnel with varying levels of experience with these instruments. The most complicated components of these methods include programming of recorders and GPS trackers as well as active tracking of the buoys to plan for retrievals. During the course of the survey, we replaced our GPS tracking instruments with an easy-to-use solar GPS and advanced our tracking capabilities to allow for automated text or email updates on buoy locations. While these modifications greatly improve usability, we also transitioned to a recorder with greater battery and hard drive capacity that required an experienced technician to prepare. 

There is a single seafloor hydrophone with low frequency capabilities (below 2 kHz) off Cordell Bank and little or no additional PAM monitoring in these sanctuaries. Seafloor hydrophones provide great temporal resolution, but their data provide information relative to a single location which may not be representative of the larger area.  Also, the low frequency capacity of this seafloor hydrophone limits detections to baleen whales (with limited detection of the low frequency component of sperm whale echolocation). 
 
The Adrift-ACCESS drifting recorders provided valuable detection of odontocetes in this region, especially for deep diving beaked whales and sperm whales, which are rarely sighted visually in these typically rough waters. Periodic deployment of mobile platforms (drifting recorders or towed hydrophone arrays) with higher frequency capabilities can complement seafloor hydrophones by covering a greater geographic range. Seasonal deployment of clustered drifting recorders can provide data to understand the variability in the various contributors to the soundscape (see online summary of Spatial Variation in Noise).

***Identify marine mammal species encountered within the Greater Farallones and Cordell Bank National Marine Sanctuaries***

Existing recorders in the Greater Farallones and Cordell Bank National Marine Sanctuaries include the NRS seafloor recorder at Cordell Bank, and the Benioff Whale Safe recorder south of the shipping lane entering San Francisco Bay.  Both recorders have low sampling rates, limiting their acoustic detection of marine mammals to baleen whales. Both of these long-term recorders provide good temporal resolution of these species; however, geographic resolution is limited to these two locations. Drifting recorders have the capabilities to record at high sampling rates, allowing detection of both baleen whales and toothed whales. 

This increased capacity provided opportunities to detect rarely deep-diving sperm whales and beaked whales. Previous sightings of sperm whales have been rare and there have been no known sightings of beaked whales in this area (to the best of our knowledge). The relatively limited effort provided by the deployment of drifting recorders has therefore provided significantly to the understanding of deep diving species within and near the combined sanctuaries.  

Sperm whales are listed as endangered and their consistent, stereotyped vocalizations make them ideal candidates for PAM.  PAM data can also be used to determine the demographic composition of sperm whales (see online summary of Sperm Whale Demographics). Beaked whales are difficult to detect, and even harder to classify to species, based on traditional visual observation methods. As with sperm whales, beaked whales are ideal candidates for PAM, and most species can be acoustically classified to species. As an example, there were no detections of beaked whales in 30 years of ACCESS surveys; however, during our limited Adrift deployments, there were numerous detections of both Baird’s beaked whales and goose-beaked whales. Beaked whales are sensitive to some anthropogenic noise sources, and we recommend improved monitoring to better understand how these species use sanctuary habitats. 

In addition to deep-diving species, there were numerous detections of dolphin and narrow-band high frequency species. Both Risso’s and Pacific-white sided dolphins were detected during these deployments, and development of improved acoustic species classifiers will likely result in identification of other dolphin species within these recordings. Dolphin schools in the California Current are frequently encountered in large, dispersed mixed species groups, and here we do not distinguish mixed species from single-species groups.

The California Current is home to four different species that produce NBHF echolocation clicks: harbor porpoise, Dall’s porpoise, pygmy sperm whales, and dwarf sperm whales. Despite the similarities in their echolocation clicks, these species inhabit different habitats and have different behaviors and life histories. Student work to develop a NBHF classifier for this study (see online summary of NBHF Classification) will be further developed in the near future and applied to these data. 

Detection of blue whales were dominated by the A/B song call types produced by males. Foraging associated ‘D’ calls were primarily detected during the post-upwelling season, and at much lower detection probabilities than A/B call types. Preliminary methods to localize low frequency sounds on clustered drifting recorders shows promise (see online summary: Modeling Habitat Use), and adoption of these methods may improve our understanding of the habitat use of these species in the greater area. Fin whales 20 Hz calls were detected with greater hourly detection during the post-upwelling deployments, and there no detection of fin whale 40 Hz calls (associated with feeding).  Both blue and fin whale calls have large detection ranges, and detection of calls does not necessarily mean that animals were near the recorder when they were detected. Preliminary methods for localization of calls from clustered deployments show promise in improving our understanding of habitat use (see online summary: Habitat Models).

Humpback whales are notoriously difficult PAM subjects due to their very active vocal behavior (in quantity and variability). Many recordings can be dominated by humpback song, and this song may be the result of a single individual. There is significant research on many of the non-song vocalizations, but detection and classification of these sounds require expertise and manual classification. The probability of detecting humpbacks was higher during the post-upwelling season for all call types, and improved tools for classifying call types could allow for improved understanding of demographic composition and habitat use. 

There were only a few gray whale detections during the post-upwelling season, and there were no detections attributed to Bryde’s, sei, or minke whales. There is a significant overlap in spectral content for humpback and gray whale calls and care should be taken when inferring gray whale presence from data with concurrent humpback whale presence. Bryde’s whales are typically found in warmer waters, though their distributions may move northward with warming ocean temperatures. Minke whale song increases during the winter season (there were no winter deployments during this study), and little is known of their non-song vocalizations. There is little known also of sei whale vocalizations. Additional research on the vocal repertoire of these species is needed. 


***Acoustic detection of fin and blue whales within and offshore the Greater Farallones and Cordell Bank National Marine Sanctuary***

An initial goal of the Adrift-ACCESS collaboration was the need for additional data on blue and fin whale distribution within and offshore of the Greater Farallones and Cordell Bank National Marine Sanctuaries. Proposed changes to the shipping lanes would move longitudinal shipping traffic offshore, and there was concern that this may increase the risk to fin whales. There were several complications that limited our ability to address this research question. There was a maximum of two deployments per survey, and many drifts were short in duration. Also, low-frequency noise complicated our ability to detect calls from these species on some portions of our deployments. In total, we were only able to collect limited data on these two species in the area of interest. Given the large detection range of these species, we are unable to determine how close the animals were to the recorder, or if the animals were within or offshore of the sanctuary boundaries. 

If these types of data are needed in the future, there are several PAM solutions that may prove beneficial. Preliminary methods have been developed to localization calls from clustered drifting recorders (see online summary: Modeling Habitat Use).  Vector sensors allow estimation of bearing angle to the sound source such that localization can be completed with one or two sensors. Alternatively, PAM-equipped gliders may be useful for offshore detection of marine mammal species. 



**Future Directions**

We are grateful for this collaboration, but unfortunately, SWFSC will no longer be conducting the Adrift project, and it is unclear if another partner will lead this effort in the future. SWFSC will be focusing their PAM efforts on underwater gliders in the wind energy areas and there are no current plans to work in this region at the moment. BOEM will be leading an effort to engage government, academic, non-profit and industry partners to develop a west coast PAM network. We encourage the sanctuaries to participate in this effort. 

The valuable insights gained on deep-diving species suggests that there is great value in coordinating some level of passive acoustic monitoring during the ACCESS surveys. This monitoring should include high sampling rates to accommodate detection of odontocete species, and may include drifting recorders, self-contained towed hydrophone arrays (towed soundtraps), or underwater gliders. Note that vessel noise interferes with baleen whale detection with towed arrays, and vessel depthsounder noise can interfere with detection of beaked whales. Most underwater gliders are costly and require highly trained technicians. Smaller user-friendly underwater gliders may provide a more cost-effective approach to offshore monitoring in the sanctuary. 

We recommend future ACCESS surveys consider collaborating with bioacoustics researchers at San Francisco State University. This collaboration would provide students with valuable hands-on experience, encourage additional student research that would serve the sanctuaries, and would be more cost-effective than collaboration with a more remote partner. 
