---
title: Beaked Whale Density Estimation Tools
---

Previous research by SWFSC found that drifting acoustic recorders could be used to estimate density of goose-beaked whales (Barlow et al. 2022), and efforts were made to streamline this analytical process to allow us to estimate beaked whale density from the Adrift survey as well as other archived and future surveys (CCES 2018 and CalCurCEAS 2024). Development of the RoboJ tool to streamline a systematic approach to density estimation was based off the process developed by SWFSC in (Barlow et al. 2022) and it was generalized for adoption by other researchers (see RoboJ GitHub Repository ). While most of the process is now streamlined, there remains a significant manual effort for identifying acoustic events. Our team initiated a process for improving automation of this tedious process, however they were unable to complete the automation of identifying acoustic events and we recommend investing in this development in the future (see Appendix: Open Science for more details on development of a beaked whale matched template classifier). The RoboJ tool has been tested by colleagues at Pacific Islands Fisheries Science Center, and documentation and final preparation of the software is underway.

RoboJ Pipeline:

-   ·        Incorporates acoustic detections stored in PAMGuard databases and binaries.

-   ·        Estimate detection range based on incoming bearing angle, presumed foraging depth, and modeled sound speed profile at each position.

-   ·        Estimate detection function for recorders

The original research was developed for the PASCAL dataset, and we have prepared the CCES 2018 dataset for analysis, but we were unable to complete the analysis in the timeframe of this study. These methods will be used for the CalCurCEAS 2024 survey data, and if opportunity allows, analysis will also be completed for the CCES 2018 dataset.

Future research should consider (1) funding further development of an automated approach to acoustic event delineation, (2) beaked whale density estimation for the Adrift dataset, and (3) expansion of this analysis to species beyond goose-beaked whales.
