---
title: Data Sharing
---

NOAA is committed to increasing the accessibility of publications and digital data produced by federal researchers through the Public Access to Research Results. Publications (including reports) can be accessed at the NOAA Institutional Repository. Raw acoustic data (wav files) are stored at the NCEI and can be accessed after an initial waiting period required as part of the NOAA Fisheries agreement with the U.S. Navy. Metadata include information related to data collection (hardware characteristics, geopositions, recording specifications), soundscape metrics, and species acoustic detection data. Recording metadata associated with data collection and Soundscape metrics will be stored at NCEI. Acoustic detection of species will be accessible via [PACM](https://apps-nefsc.fisheries.noaa.gov/pacm) . Details on data archive and sharing methods are provided in our [Github analysis methods](https://sael-swfsc.github.io/adrift-analysis-methods/content/DataArchive/TethysDeployments.html).

In addition to public sharing of our research results, the Southwest Acoustic Ecology Lab firmly believes that analysis methods should be publicly accessible. We dedicated time to develop a streamlined approach to data analysis, data visualization, and archival processes to create a reproducible product. These include developing methods in open-source software and publishing analytical methods as R packages, available on [CRAN](https://cran.r-project.org) (Comprehensive R Archive Network). This approach requires substantial initial investment, but ultimately provides improved efficiency and reproducible research results. Development of open-source analytical methods for detecting baleen whales required additional research and development investment; complications that arose due to the COVID-19 pandemic thwarted these efforts. Many of these data methods and data products are being adopted by other researchers and across NOAA Fisheries more broadly, providing future cost savings to NOAA and BOEM into the future.

Additional details regarding Open Science Efforts can be found in Open Science.
