---
title: Marine Mammal Detection Summary 
---

The purpose of the Adrift project was to collect baseline data to identify which marine mammal species frequent the Morro Bay, Humboldt, and Oregon Wind Energy Areas, and to describe their seasonal occurrence and distribution within the greater California Current Ecosystem. Different call types are understood to be associated with specific behaviors and therefore provide information related to habitat use. For mysticete (baleen) whales, we focused on blue whales (*Balaenoptera musculus*), fin whales (*B. physalus*), Bryde’s whales (*B. edeni*), sei whales (*B. borealis*), humpback whales (*Megaptera novaeangliae*), gray whale (*Eschrichtius robustus*) and minke whales (*B. acutorostrata*). For odontocetes (toothed whales), we focused on sperm whales (*Physeter macrocephalus*), beaked whales (all regional species), dolphins (including Risso’s dolphins, *Grampus griseus*, and Pacific white-sided dolphins, *Lagenorhynchus obliquidens*), and narrow band high frequency (NBHF) species (harbor porpoise, *Phoceona phocoena*, Dall’s porpoise, *Phocoenoides dalli*, and *Kogia* spp.). Passive acoustic monitoring relies on sounds produced by animals for detection, and therefore PAM studies cannot identify the absence of animals. Data analysis for fin, sei, and Bryde’s whales was contracted through OSA ([Ocean Science Analytics](https://www.oceanscienceanalytics.com/)). Specific details on detection methods are provided in our [GitHub Analysis Methods](https://sael-swfsc.github.io/adrift-analysis-methods/).

Raw data were shipped from regional partners to SWFSC for archiving, pre-processing, and acoustic analysis of marine mammals and ambient noise (soundscape). Deployment metadata and species detection metadata were stored to a Tethys database stored on a local server. Data and metadata were archived to National Centers for Environmental Information (NCEI) and detection data products were archived at the Pacific Acoustic Cetacean Map (PACM) (see Data Sharing).

Prior to analysis, compressed SUD (Symantec UndoData) data files stored on the SoundTrap recorders were downloaded, extracted, and decimated to 500Hz, 12 kHz, and 48 kHz. A series of full bandwidth Long Term Spectra Averages (LTSAs) were generated using Triton software with 200 Hz, 5 s resolution. LTSAs were then scanned to assess overall data quality and to identify recording data start and end times. A series of custom quality assurance and quality control functions provided a check for appropriate time format, eliminated spurious GPS tracks, and identified unexpected recording gaps. More information on pre-processing methods can be found on [GitHub](https://sael-swfsc.github.io/adrift-analysis-methods/content/DataArchive/DataPrep.html).

Our intention was to develop a streamlined open-source workflow for passive acoustic analysis that would promote reproducible research. Raw recording data were processed and analyzed to detect the presence of calls associated with mysticete species (blue, fin, Bryde's, sei, humpback, gray, and minke whales) and odontocete species (sperm whales, beaked whales, dolphins, and species known to produce narrow-band high frequency sounds (porpoise and Kogia spp.)). Presence of sounds were noted in hourly bins; and detection methods varied by species. Analysis was not conducted on recordings deemed unusable due to excessive self-noise. In addition, an acoustic event of unknown species (possible sei/blue whale) was detected on Adrift-060 off Oregon in 2023. This extended acoustic encounter includes a number of frequency-modulated call types. More information can be found in our GitHub Repository.

Initially, our ability to access and process our archived data was extremely limited due to the COVID-19 pandemic. Our archived data was largely inaccessible for the first 6 - 12 months, and we were limited to small scale processing on our laptops. Early on we initiated the purchase of a larger server that would allow larger scale remote processing of archived data, but supply chain issues and a series of technical problems delayed use for an additional 18 months. Between accessibility and supply chain issues associated with the pandemic, processing archived data took significantly more time than expected. The cumulative effect of these problems resulted in decreased opportunity to provide higher level analysis within the timeframe of this study. Where possible, we have provided preliminary analysis within the appendices to understand potential for future analysis.
