---
title: Outreach
---

The study of ocean sound is interdisciplinary and provides a natural opportunity for community engagement in formal education (K-12), informal science learning (museums), and online crowd-source citizen science participation. Our team engaged with students, journalists, and educators to develop materials and tools to make our science accessible to the public. Education and Outreach efforts included mentoring students and interns on authentic research projects, inviting journalists to participate in fieldwork, collaborating with educators to develop lesson plans for many age groups, and developing a preliminary crowd-sourced Zooniverse platform for community involvement in our research.

The interdisciplinary nature of passive acoustics along with the natural appeal of whales and dolphins provides an opportunity for engaging the public in science and the scientific process. To that end, we developed a series of education and outreach materials to reach a diverse populace.

In 2020 we collaborated with San Diego Unified School District (SDUSD) to host a teachers' workshop to develop a series of phenomena-based instructional curricula. Lessons aligned with Next Generation Science Standards and included instructional units for elementary schools ([Dolphins have Needs](https://drive.google.com/file/d/1VE2-jXCJet4iO_4bWywwW0dPtOK1BcLA/view) ), Middle School ([You can recognize different species by the sounds they make](https://drive.google.com/file/d/1MsorXXkcHk8YNyHgldJ_-ApASLcEkoJy/view) ) and High School ([Ocean noise impacts marine mammals](https://drive.google.com/file/d/17qMPka0tTKjmF8jlAQD24QiWRzs3E9P4/view) ). Lessons plans are publicly available on the [Project Phenomena Database website.](https://www.sdcoe.net/ngss/phenomena-and-the-ngss)

Data Nuggets are free classroom activities designed to bring contemporary research and authentic data into the classroom. Data Nuggets were recommended by our teacher collaborators during the SDUSD workshop as a highly useful format for Science Technology Engineering Mathematics in the classroom. We collaborated with Data Nuggets to create '[Eavesdropping on the Ocean](https://datanuggets.org/2024/04/eavesdropping-on-the-ocean)’ . This Data Nugget provides background on the research question, authentic data to allow classrooms to work with real data to apply to the research question, as well as links for additional information. This has been made publicly available for teachers at no cost.

In addition, we initiated a Zooniverse Project, [Ocean Voices](https://www.zooniverse.org/projects/annelistens/ocean-voices) . The initial intention of this effort was to use citizen scientists to label datasets as either humpback whales or ship noise; these annotations would then be used to develop an improved machine learning classifier. This required significant effort to automate development of paired spectrograms and acoustic recordings for the platform. The citizen scientist portion of this project will be delayed until future continuation of the work done during the Adrift study, however, the platform can currently function as an education learning tool. The software tools designed to manipulate acoustic data for input to Zooniverse are available on [GitHub](https://github.com/TaikiSan21/wav2mp3).

Our periodic 'Sound Bytes' blog provides a general audience with insight into the day-to-day work behind the science. Topics range from '[Lessons learned from Fishermen](https://www.fisheries.noaa.gov/science-blog/sound-bytes-fresh-catch-lessons-fisherman)' to how we ‘[Gear up for Fieldwork](https://www.fisheries.noaa.gov/science-blog/sound-bytes-gearing-field-work)’ to how we ‘[Hook young scientists on Research](https://www.fisheries.noaa.gov/science-blog/sound-bytes-hooking-young-students-research)’. We have had a host of guest bloggers, including students, interns, and collaborators. These blogs are shared on NOAA's [website](https://www.fisheries.noaa.gov/taxonomy/term/1000356091) and they have been promoted through numerous NOAA newsletters. Cory Hom-Weaver led these efforts and was recognized for an Award by NOAA's Southwest Fisheries Science Center for the excellent education and outreach provided by the Sound Bytes blog.

Additional details regarding our Education and Outreach efforts can be found in Appendix K.
