---
title: Ship Noise 
---

Ships produce different sounds while operating, such as impulsive signals from ship propeller cavitation or echosounder signals that can be easily identified in the LTSA and confirmed with a spectrogram. Vessel noise was identified by a trained analyst scanning 1-hour LTSA windows using the Logger Remora in Triton (100 Hz and 5 s resolution). Once a ship was identified, 10 s spectrograms were used to confirm identification (2000 point FFT, 75% overlap). Ships were either logged as being broadband (high amplitude with frequency content above 5 kHz) or narrowband/low frequency (lower amplitude). Ship noise was assessed in full for the Adrift study and in part for CCES (not analyzed for PASCAL). Additional details are provided in [Github online analysis methods](https://sael-swfsc.github.io/adrift-analysis-methods/content/Soundscapes/Metrics.html#detect-vessels). The manual methods used in this study were time consuming, but our initial efforts to analyze data with an existing ship detector found that the detector was unreliable on identifying ship tracks with our dataset. We recommend development of an open-source approach to vessel detection that includes classification of vessels to vessel type, and integration of this data into a systematic approach to quantifying the contribution of ship noise to the soundscape.

The percent of recording hours with vessel presence varied across region, season, and time of day (@fig-ADRIFT_ShipPresence_SeasonRegion). Vessel presence was higher in Oregon and Humboldt than in San Francisco or Morro Bay. Vessel presence in Humboldt shifted from night-time during the upwelling season to daytime during the post-upwelling season (summer), with winter variability likely relating to low effort. Morro Bay region experienced the lowest amount of vessel traffic, with extremely low levels of vessel traffic (\<20%) detected in the post-upwelling season.

Hourly presence of ships in San Francisco appears to be lower than other regions (@fig-ADRIFT_ShipPresence_SeasonRegion). Overall sound levels were much higher in this region (@fig-ADRIFT_PSD_SeasonRegion), and may have masked some individual ship passages. Future work can include an Automatic Identification System metric such as the number of unique large vessels with relatively close approaches.

![Polar plots of seasonal detection of ship noise in Oregon, Humboldt, San Francisco, and Morro Bay regions. The hourly percent of effort with vessel detections is shown in color ranging from dark blue (0%) to yellow (50%). The diurnal variation in vessel noise is shown by detection in bins on polar plot ranging from 0 to 24 hr of the day (UTC, Universal Time Coordinated).](/figs/ADRIFT_ShipPresence_SeasonRegion.png){#fig-ADRIFT_ShipPresence_SeasonRegion fig-alt="Polar plots of ship noise by season (upwelling on left, post-upwelling in center, and winter on right) and region (Oregon at top, then Humboldt, San Francisco, and Morro Bay at the bottom). Each polar plot shows the percent of detections as a colored histogram (percent detections range from 0 in dark blue to 0.5 in bright yellow) for each hour of the day. In Humboldt, more ships were detected in the middle of the night during the upwelling season, in the afternoon during the post-upwelling season, and in the early morning during the (limited) winter data. Oregon had a larger number of ships detected late at night during the post-upwelling season, and both Morro Bay and San Francisco had relatively low percentages of detections compared to other regions."}

{{< include soundscape.qmd >}}
