---
title: Software 
editor: 
  markdown: 
    wrap: sentence
bibliography: references.bib
---

The Southwest Acoustic Ecology Lab firmly believes that analysis methods should be publicly accessible.
We dedicated time to develop a streamlined approach to data analysis, data visualization, and archival processes to create a reproducible product.
These include developing methods in open-source software and publishing analytical methods as R packages, available on CRAN (Comprehensive R Archive Network).
Open-source software developed as a part of this project include:

## PAMpal

PAMpal is an R package for processing passive acoustic data collected using [PAMGuard](PAMGuard.org) software.
PAMpal was initially funded by NOAA's Advanced Sampling Technology Working Group; additional functionality to support the Adrift project was made to PAMpal to allow others to benefit from these developments.
PAMpal is increasingly being adopted by scientists using mobile platforms.

-   [PAMpal on CRAN](https://cran.r-project.org/package=PAMpal)

-   [PAMpal User Guide](https://taikisan21.github.io/PAMpal)

-   [PAMpal GitHub](https://github.com/TaikiSan21/PAMpal)

## PAMscapes

The NOAA-funded "Biotic, Abiotic, and Anthropogenic Contributors to the Soundscapes: Development of an Open -Source Method for Data Integration & Visualization" developed the PAMscapes R package, including several of the visualizations used in this report.
This effort also allows for integration of Automatic Identification System ship tracks and weather data with acoustic detections from PAMpal.

-   [Final report](https://github.com/shannonrankin/fossa_soundscape/files/13231870/Rankin.etal_FOSSA.Soundscape.Report_OAP2023.pdf)

-   [PAMscapes on CRAN](https://cran.r-project.org/package=PAMscapes)

-   [PAMscapes GitHub](https://github.com/TaikiSan21/PAMscapes)

## Beaked Whale Analytical Tools

Previous research by SWFSC found that drifting acoustic recorders could be used to estimate density of goose-beaked whales [@barlow2021], and efforts were made to streamline this analytical process to allow us to estimate beaked whale density from the Adrift survey as well as other archived and future surveys (CCES 2018 and CalCurCEAS 2024).
Development of the RoboJ tool to streamline a systematic approach to density estimation was based off the process developed by SWFSC in [@barlow2021] and it was generalized for adoption by other researchers (see[RoboJ GitHub Repository](https://github.com/TaikiSan21/RoboJ)).
While most of the process is now streamlined, there remains a significant manual effort for identifying acoustic events.
Our team initiated a process for improving automation of this tedious process, however they were unable to complete the automation of identifying acoustic events and we recommend investing in this development in the future.
The RoboJ tool has been tested by colleagues at Pacific Islands Fisheries Science Center, and documentation and final preparation of the software is underway.

### ***RoboJ***

RoboJ is an extension of work by Jay Barlow and Jeff Moore to estimate the density of beaked whales using detections from drifting recorders [@barlow2021].The methods use the received angles of beaked whale events combined with known dive depth distributions to estimate the distance to the calling animals, which then is used to estimate the density using more traditional methods.Development is still ongoing, but near-final code for this project is available on [RoboJ GitHub](https://github.com/TaikiSan21/RoboJ).

RoboJ Pipeline:

-   Incorporates acoustic detections stored in PAMGuard databases and binaries.

-   Estimate detection range based on incoming bearing angle, presumed foraging depth, and modeled sound speed profile at each position.

-   Estimate detection function for recorders

The original research was developed for the PASCAL dataset, and we have prepared the CCES 2018 dataset for analysis, but we were unable to complete the analysis in the timeframe of this study.
These methods will be used for the CalCurCEAS 2024 survey data, and if opportunity allows, analysis will also be completed for the CCES 2018 dataset.

Future research should consider (1) funding further development of an automated approach to acoustic event delineation, (2) beaked whale density estimation for the Adrift dataset, and (3) expansion of this analysis to species beyond goose-beaked whales.

### ***Beaked Whale Event Detector***

Anne Simonis and Taiki Sakai developed a preliminary automated workflow for identifying and classifying beaked whale events.
The initial approach used a Match Template Classifier (MTC) to identify candidate beaked whale clicks and group these into events.
Initial attempts to use the MTC-defined events to train a BANTER model were not successful enough to deploy the model on new Adrift study data, so an attempt was made to incorporate a computer vision-based model to add additional information for the BANTER model.
This combined outputs from a computer vision model that was trained on other beaked whale data with the original MTC data.
Preliminary results suggest there is a need for further development of the initial MTC detection step.

The combined models results were promising but required improved training data.

-   Detailed project status report can be found on [GitHub](https://github.com/SAEL-SWFSC/Adrift/blob/main/supplement/Simonis.Sakai_BeakerMTC_May2024.pdf).

-   Detailed summary of the original computer-vision model can be found on [GitHub](https://github.com/SAEL-SWFSC/Adrift/blob/main/supplement/TSakai_beakerVisionModel_May2024.pdf).

## Fin Model

Cory Hom-Weaver and Taiki Sakai developed a random forest model for classifying fin whale 20 Hz calls.
This method uses PAMGuard's click detector and PAMpal to process click data and create a model training dataset.
The model was trained on a subset of manually annotated Adrift study data, and results were validated on a subset of data.
The validation set was used to identify criteria for manually reviewing the predictions, and then the model was used to predict on the remainder of Adrift study data.
A set of functions to create review products for each predicted drift allowed the analyst to quickly scan data to verify fin whale presence.

-   Code for creating review products and model training is available on [GitHub](https://github.com/TaikiSan21/Fin_RF).
