---
title: Sperm Whales
---

::: columns
::: {.column width="40%"}

Sperm whales were detected in all regions (see table, right), with the most consistent detections and highest hourly probability of detection in the Humboldt deployments (see table, right, and @fig-AdPC_sperm_HourlyPresence). Most sperm whale detections were ‘regular’ clicks associated with feeding animals; ‘slow’ clicks (associated with adult males) were uncommon but detected in all regions except Morro Bay (see table, right). Sperm whales were detected in all regions in PASCAL and/or CCES Surveys (@fig-AdPC_sperm_HourlyPresence).

Sperm whales had been documented only 3 times in the waters offshore San Francisco in over 30 years of ACCESS visual surveys (J. Roletto, pers. comm.). Our detection of sperm whales (both regular and slow clicks) from drifting recorders deployed during the ACCESS surveys suggests that passive acoustic monitoring might improve our understanding of sperm whale distribution in the busy shipping lanes off San Francisco as well as within the combined Greater Farallones and Cordell Bank National Marine Sanctuary.

:::

::: {.column width="60%"}

```{r spermTbl, echo=FALSE, warning=FALSE, message=FALSE}
library(here)
source(here::here("R/_commonR.r"))
source(here::here("R/reportPlotFunctions.r"))

load(here("data", "Pm", "pmBin_adrift.rdata"))
binClick<-pmBinClick_adrift %>%
  mutate (Season = markSeason(pmBinClick_adrift$UTC),
          Region = map_chr(pmBinClick_adrift$Latitude, find_region)
          )%>%
  group_by(Season, Region) %>%
  dplyr::summarise(
    HourlyEffort=sum(pctEff),
    sppPres=length(which(call == "Clicks")),
    HourlyProb = sppPres/HourlyEffort,
    n=n()
  )
binClick<- binClick[,c(1, 2, 5, 6)]
binClick$CallType <- "Regular Clicks"
binClick <- binClick[!is.na(binClick$Region),]

binSlow<-pmBinSlow_adrift%>%
  mutate (Season = markSeason(pmBinSlow_adrift$UTC),
          Region = map_chr(pmBinSlow_adrift$Latitude, find_region),
          CallType = "Slow Clicks"
          )%>%
  group_by(Season, Region) %>%
  dplyr::summarise(
    HourlyEffort=sum(pctEff),
    sppPres=length(which(call == "Slow Clicks")),
    HourlyProb = sppPres/HourlyEffort,
    n=n()
  )
binSlow<- binSlow[,c(1, 2, 5, 6)]
binSlow$CallType <- "Slow Clicks"
binSlow <- binSlow[!is.na(binSlow$Region),]




dfSummary <- rbind(binClick, binSlow)

detTbl <- dfSummary %>%
  pivot_wider(names_from = "Season", values_from = c("HourlyProb", "n"))%>%
  mutate (Region = fct_relevel(Region, c("Oregon", "Humboldt", "San Francisco", "Morro Bay")))%>%
  arrange(Region)%>%
  gt(
  groupname_col = "CallType",
  rowname_col = "Region"
  )%>%
  DetTableTheme508()
detTbl
```

:::
:::



A pilot study examining the potential estimation of body size based on inter-pulse and inter-click intervals found that sperm whale groups detected during November deployments in Morro Bay were comprised of females and juvenile males (see Appendix D). Sperm whales are protected under the endangered species act, and we recommend applying these methods to archived and future acoustic data to improve our understanding of sperm whale demographics within the regional WEAs as well as the greater California Current.


![Hourly sperm whale events by month, region for Adrift and combined PASCAL, CCES surveys. Hourly sperm whale events (y axis) for different months for combined years (x axis) and for each region (Oregon, Humboldt, San Francisco, and Morro Bay) for Adrift (left) and combined PASCAL and CCES (right). Hourly presence for duty-cycled data relates to the portion of the hour included in the duty cycled data. Black lines represent total available hours (effort) and red lines represent hours with detections. Blue shading represents winter, green represents upwelling, and yellow represents the post-upwelling oceanographic season.](/figs/AdPC_sperm_HourlyPresence.png){#fig-AdPC_sperm_HourlyPresence fig-alt="Hourly presence of sperm whales detected during the Adrift study (left graph) and the combined PASCAL/CCES surveys (right graph). Detections in Oregon are shown in the top graphs, then Humboldt, San Francisco, and Morro Bay at the bottom. The number of hours is provided on the x-axis, and the date on the y-axis, with seasons shaded in blue for winter, green for upwelling, and yellow for the post-upwelling season. Effort is outlined with a black line, and hours of effort with detections are highlighted in red. Sperm whale detections varied by region and between the Adrift and combined PASCAL/CCES surveys, with higher detection rates in the Humboldt region."}





Detailed methods are provided in our [GitHub online analysis methods](https://sael-swfsc.github.io/adrift-analysis-methods/content/ToothedWhales/SpermWhales-Detection.html).

Additionally, a pilot study was conducted to investigate the potential for assessing sperm whale demographics by analyzing inter-click and inter-pulse intervals (see Appendix D).
