---
title: Summary of Results
---

The Adrift in the California Current survey was intended to provide additional baseline data on marine mammals and the marine soundscape to inform management of offshore renewable resource development in the California Current. In addition to conducting data collection efforts in and around the Morro Bay, Humboldt, and Oregon WEAs, we also analyzed archived data from previous large scale acoustic surveys.

The first phase of Adrift was initiated in June 2020 off Northern California, with a special focus on the Humboldt WEA. We partnered with NOAA Sanctuaries to provide additional sampling off San Francisco between late Spring and late Summer. Initial deployments were delayed until August 2021 due to the COVID-19 pandemic. The second phase extended this effort to the Morro Bay WEA offshore Central California in 2021. In 2022 we initiated a pilot study to examine the potential for extending this study northward to include offshore Oregon. Data collection efforts were severely limited due to the COVID-19 pandemic as well as inclement weather and oceanographic conditions aggravated by La Niña. Despite these limitations, we deployed 90 drifting recorders in our four study areas for a total of 8,736 recording hours.

Prior to this study, NOAA had successfully deployed drifting acoustic recorders during two large-scale surveys and developed methods to estimate beaked whale density for the larger California Current region. Southwest Fisheries Science Center in partnership with BOEM’s Pacific Region is currently conducting an additional large-scale survey with drifting acoustic recorders (Pacific Marine Assessment Partnership for Protected Species – PacMAPPS II/CalCurCEAS).

While we have been successful using drifting recorders during these large-scale surveys during the late post-upwelling season, we encountered significant challenges in using them during other oceanographic seasons. There were multiple cases of equipment and data loss, especially during the initial deployments. Losses were due to a variety of reasons, including inclement weather, strong currents, and recorder failures. We mitigated these problems through modifying components and altering survey methods. A number of gear modifications were made to improve robustness and to decrease self-noise that interfered with recording quality.

Drifting acoustic recorders provide a low-cost alternative to traditional PAM systems and they can provide additional geographic and temporal resolution in remote offshore areas. Clustered drifting recorders provide an opportunity to improve our understanding of the spatial and temporal variability of the contributors to the soundscape. Preliminary results suggest that clustered drifting recorders can be used to reduce the possible range of possible source location for sound sources (see Appendix H) and can provide information on the spatial variation in soundscape (see Appendix I). Drifting recorders were deployed in clusters of 4 drifting recorders in Humboldt and Oregon study areas, and in clusters of 8 in the Morro Bay Study area. In some cases, drifting recorders in close proximity to each other followed dramatically different drift trajectories.

Below we present a summary of our results and a summary of recommendations for future work.

9.1. Summary of Results Drifting acoustic recorders can provide high quality PAM for some offshore regions, especially when deployed in clusters to enhance spatial monitoring. Pilot studies are recommended for new regions, to ensure that environmental conditions and local resources support effective sampling. Hardware continues to evolve to allow for improved data collection, and newly developed sub-surface drifting recorders may prove preferable to existing drifting recorders with surface buoys. Our experience suggests that deployment of clustered drifting recorders seasonally in areas of interest could provide additional spatial context to co-located seafloor recorders. Seasonal sampling of these clustered deployments during collaborative cruises, such as our Morro Bay fieldwork, promotes collaborative science and reduces vessel costs.

This dataset provides additional (publicly available) data to support management needs as well as new information on several species. Data analysis included most cetacean species found within the California Current; though several rare species (north Pacific right whales, pilot whales) were not included, nor were pinnipeds. The data are publicly available for future expansion of analysis to include these species.

Sperm whales are listed as endangered and their consistent, stereotyped vocalizations make them ideal candidates for PAM. Sperm whales were detected in all study areas, with high detection probabilities in Humboldt during all seasons. PAM data can also be used to determine the demographic composition of sperm whales, and a pilot study of a Morro Bay dataset found that all animals were social groups consisting of females and their young, or juvenile males. There was insufficient time to complete this analysis for our entire archived data, but future research should include acoustic estimations of demographic composition for sperm whales.

Beaked whales are difficult to detect, and even harder to classify to species, based on traditional visual observation methods. As with sperm whales, beaked whales are ideal candidates for PAM, and most species can be acoustically classified to species. As an example, there were no detections of beaked whales in 30 years of ACCESS surveys; however, during our limited Adrift deployments, there were numerous detections of both Baird’s beaked whales and goose-beaked whales. Beaked whales were found in all regions, with goose-beaked whales the most common species overall (though none of these species were detected in either Humboldt or Oregon). During the Adrift study, methods to estimate beaked whale density using drifting recorders were automated (to improve efficiency), and data were prepared for analysis, but we were unable to complete this analysis during the time available.

Many of the beaked whales detected in Morro Bay co-occurred with echolocating dolphins. The vertical hydrophone array of the drifting recorders allows for estimation of bearing angles for incoming echolocation clicks, and subsequent differentiation between echolocating beaked whales at depth from echolocating dolphins near the surface. By segregating the echolocation clicks based on bearing angle, we were able to identify the small numbers of beaked whale clicks within thousands (or even millions) of echolocating dolphins. The co-occurrence of dolphins and beaked whales has not been previously reported, and it is unclear what may bring these species together. The likelihood of detecting beaked whales in these mixed species encounters would have been very low if recordings were collected from a single, seafloor sensor or from towed hydrophone arrays.

The California Current has a high diversity of dolphin species, and species classification is difficult. While there are several potential approaches to species classification, they have either been developed for towed arrays at the surface (Rankin et al. 2017) or for seafloor hydrophones (Frasier et al. 2017). Currently, there is insufficient validated data for drifting recorders to test the efficacy of existing classifiers on these data, or to develop a drifting-recorder specific classifier. That said, there are robust methods to identify echolocation clicks from Pacific white-sided dolphins and Risso’s dolphins. Dolphin schools in central and northern California are frequently encountered in large, dispersed mixed species groups, and here we do not distinguish mixed species from single-species groups.

Risso’s dolphins were detected in all regions except Oregon, and had the highest probability of detection during the upwelling season in Humboldt. The dominant click type detected was the ‘Pelagic Pacific’ type identified by Soldevilla 2017. Pacific white-sided dolphins were detected in all regions, with higher detection probabilities in the post-upwelling season for Humboldt and San Francisco, and during the upwelling season in Morro Bay. The dominant click type for Pacific white-sided dolphins was ‘Type A’, though ‘Type B’ click types were detected northward of the range identified in Soldevilla 2010. There were relatively few detections of ‘Unidentified odontocetes’ during the post-upwelling season in Oregon and Morro Bay.

The California Current is home to four different species that produce NBHF echolocation clicks: harbor porpoise, Dall’s porpoise, pygmy sperm whales, and dwarf sperm whales. Despite the similarities in their echolocation clicks, these species inhabit different habitats and have different behaviors and life histories. Student work to develop a NBHF classifier for this study (see Appendix F) will be further developed in the near future and applied to these data to expand our understanding of the distribution of these species in the California Current as well as the regional WEAs.

Blue whales were detected in all regions except Oregon, and the probability of detecting blue whales was higher during the post-upwelling season. Blue whale acoustic detections were dominated by the A/B song call types produced by males. Foraging associated ‘D’ calls were primarily detected during the post-upwelling season, and at much lower detection probabilities than A/B call types. Blue whale calls, especially the ‘B’ call type, can be detected at great ranges and the range of potential sound source locations can be large. Preliminary methods to localize low frequency sounds on clustered drifting recorders shows promise (see Appendix H), and adoption of these methods may improve our understanding of the habitat use of these species in the greater area.

Fin whales were detected throughout the study area at different times of year. Fin whale 20 Hz pulses had a higher detection probability during the post-upwelling season for all regions. Here we did not differentiate between irregular and stereotyped patterns of 20 Hz calls. The 40 Hz call associated with foraging were detected off Oregon and during the post-upwelling season off Morro Bay. These data were used to improve and test a fin whale classifier with excellent results (Appendix G), and future adoption of these methods may allow for an improved approach of classifying variability in fin whale call patterns.

Humpback whales were detected during most deployments, though detection off Oregon was relatively low. The probability of detecting humpbacks was higher for the upwelling season for Morro Bay, while the probability of detecting humpbacks was lower during the upwelling season for both San Francisco and Humboldt. While there were few detections of humpback whales during the late June/early July surveys off Morro Bay, these animals were frequently sighted nearshore, highlighting the variability of their distribution within these greater regions.

Humpback whales are notoriously difficult PAM subjects due to their very active vocal behavior (in quantity and variability). Many recordings can be dominated by humpback song, and this song may be the result of a single individual. There is significant research on many of the non-song vocalizations, but detection and classification of these sounds require expertise and manual classification. There are significant numbers of annotated datasets, and development of a machine learning method to detect and classify these sounds would allow researchers to better understand how the detection of humpback sounds can inform the demographic composition and habitat use of these species throughout the California Current.

Bryde’s whales occur in the tropical and sub-tropical Pacific Ocean, with occasional incursions into the Southern California Bight. We did not detect sounds associated with Bryde’s whales in this analysis, but we do expect these species may become more common with global ocean warming.

Little is known of the vocal repertoire of sei whales, and our research only found one potential sei whale acoustic detection. Future research should take advantage of opportunities to understand the vocal repertoire of sei whales in the North Pacific Ocean.

Most gray whales use more shallow, coastal waters for their migration between their feeding grounds in the north and their winter breeding grounds in Baja California. Gray whales were detected off Oregon, where there is a resident population, and during the post-upwelling season in the San Francisco and Morro Bay areas. There is a significant overlap in spectral content for humpback and gray whale calls and care should be taken when inferring gray whale presence from data with concurrent humpback whale presence.

There were no detections of minke whale ‘boings’ during our Adrift study, and only a few during the combined PASCAL/CCES surveys. There was one visual sighting of a minke whale in coastal waters near Morro Bay harbor in November 2023; however, there were no recordings during our offshore drifts during this same survey. The lack of detections could be related to low seasonal population densities or that calling animals use coastal waters.

In addition to detecting marine mammal species, we manually detected ship tracks in these data (existing ship noise detectors were not reliable on our data). The percent of recording hours with vessel presence varied across region, season, and time of day, and vessel presence was generally higher in Oregon and Humboldt than in San Francisco or Morro Bay. Vessel presence in Humboldt shifted from night-time during the upwelling season to daytime during the post-upwelling season (summer), with winter variability likely relating to low effort. Morro Bay region experienced the lowest amount of vessel traffic, with extremely low levels of vessel traffic (\<20%) detected in the post-upwelling season. The relatively low detection of ships off San Francisco may be related to masking of individual ship passages due to the overall higher sound levels in this region. Development of a standardized approach to detecting vessels that works across platforms and compensates for elevated ambient noise due to high vessel track is warranted.

These biological and anthropogenic sounds contribute to the overall soundscape, and measurement of sound levels allows us to examine variation in the soundscape over time. Soundscape metrics aligned with previously analyzed SanctSound data for consistency, but preferred methods recommend reporting sound levels in hybrid millidecade bands. Our soundscape data will be publicly accessible to allow for this conversion. Our results show variability in sound levels over time and space, with general noise levels ranging from 50 dB re 1uPa to nearly 150 dB re 1 uPa (and the highest density of sound in the 75 – 100 dB range).

The marine soundscape includes sounds associated with physical drivers (rain, waves, earthquakes), biological sources (sounds produced by marine mammals, fish, and invertebrates), as well as anthropogenic sounds. In this study we examined sounds attributed to a number of marine mammal species as well as ship noise. We also developed automated methods to integrate these data to better understand these various contributors to the soundscape, and how they change over time. While we had limited time to conduct advanced analyses, our research efforts took a significant step forward so that future researchers can more readily integrate these methods into their analyses. These methods will be adopted and expanded by NOAA PAM researchers at a national scale as part of a new PAM strategic initiative.

All data have been publicly archived to [NCEI](https://www.ncei.noaa.gov/maps/passive-acoustic-data/) and detection data archived to [PACM](https://apps-nefsc.fisheries.noaa.gov/pacm).
