
```{r, include=FALSE}
#Load packages and background data/functions
library(here)
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
source(here::here("R/_commonR.r"))
source(here::here("R/deployDetails.r"))
```


```{r, CCESdeployExport1, include=FALSE}
#Prepare data, export as an html. Then open in Excel and within Word, open as an excel spreadsheet. Modify within word.
    survey <- "CCES" #Choose "ADRIFT" or "CCES" or "PASCAL"

    #Load Data and prep Data
    deployDetails_all <- read.csv(here ("output", "deployDetails.csv"))

    deployDetails_all$DutyCycle <- if_else(deployDetails_all$RecordingDuration_m != "Continuous",  paste(deployDetails_all$RecordingDuration_m, "min per", deployDetails_all$RecordingInterval_m), "Continuous")

    goodCol <- c("Drift_ID", "Site",  "Status",  "Deployment_Date", "Deployment_Latitude", "Deployment_Longitude",   "Recovery_Date", "Recovery_Latitude", "Recovery_Longitude",  "Recorder", "Recorder", "SampleRate_kHz",  "DutyCycle",  "Deployment_Depth_m.", "Data_Start", "Data_End" )
    dates2change <- c("Deployment_Date", "Recovery_Date", "Data_Start", "Data_End")

    deployDetails <- deployDetails_all%>%
      filter(Project == survey) %>%
      rename(Recorder = Type, Drift_ID = Data_ID) %>%
      arrange("Deployment_Date")%>%
      select(goodCol) 
    
deployDetails$Deployment_Date <- substr(deployDetails$Deployment_Date, 1, 10)
deployDetails$Recovery_Date <- substr(deployDetails$Recovery_Date, 1, 10)
deployDetails$Data_Start <- substr(deployDetails$Data_Start, 1, 10)
deployDetails$Data_End<- substr(deployDetails$Data_End, 1, 10)
```
```{r, CCESdeployExport2, include=FALSE}
#Change Column Labels, decimal places 
 
DeployTable_CCES_ex <- deployDetails %>%
  gt()%>%
  sub_missing(missing_text = "--")%>%
    fmt_number(
    columns = c("Deployment_Latitude", "Deployment_Longitude", "Recovery_Latitude",
    "Recovery_Longitude"),
    decimals = 2
  ) %>%
    cols_align(
    align = "center"
  ) %>%
  cols_label(
      Drift_ID = "Drift ID",
      Deployment_Date = "Deploy Date",
      Deployment_Latitude = "Deploy Lat",
      Deployment_Longitude = "Deploy Long",
      Recovery_Date = "Recover Date",
      Recovery_Latitude = "Recover Lat",
      Recovery_Longitude = "Recover Long",
      SampleRate_kHz = "SR (kHz)",
      DutyCycle = "Duty Cycle",
      Deployment_Depth_m. = "HP Depth (m)",
      Data_Start = "Data Start Date",
      Data_End = "Data End Date"
    )%>%
  sub_values(
    columns = "Status",
    values = c("Lost", "Sunk"),
    replacement = "Failed"
  )
DeployTable_CCES_ex  
gtsave(DeployTable_CCES_ex, filename = here("output", "DeployTable_CCES.html"))

```


```{r, Complete Deployment Table CCES}
# Make Expanded Table for Appendix
DeployTable_CCES <- deployDetails %>% 
  gt()%>%
  tableTheme()%>%
  # tab_header('CCES Survey') %>%
  sub_missing(missing_text = "--")%>%
  tab_spanner(
    label = "Deployment",
    columns = c(Deployment_Date, Deployment_Latitude, Deployment_Longitude)
  ) %>%
  tab_spanner(
    label = "Retrieval",
    columns = c(Recovery_Date, Recovery_Latitude, Recovery_Longitude)
  )%>%
    tab_spanner(
    label = "Recording Specifications",
    columns = c(Recorder, SampleRate_kHz, DutyCycle, Deployment_Depth_m.)
  )%>%
    fmt_number(
    columns = c("Deployment_Latitude", "Deployment_Longitude", "Recovery_Latitude",
    "Recovery_Longitude"),
    decimals = 2
  ) %>%
    cols_align(
    align = "center"
  ) %>%
  cols_label(
      Drift_ID = "Drift ID",
      Deployment_Date = "Date",
      Deployment_Latitude = "Lat",
      Deployment_Longitude = "Long",
      Recovery_Date = "Date",
      Recovery_Latitude = "Lat",
      Recovery_Longitude = "Long",
      SampleRate_kHz = "SR (kHz)",
      DutyCycle = "Duty Cycle",
      Deployment_Depth_m. = "HP Depth (m)",
      Data_Start = "Data Start Date",
      Data_End = "Data End Date"
    )%>%
  # tab_options(
  #   table.width = pct(70),
  #   table.font.size = px(10)
  # )%>%
  sub_values(
    columns = "Status",
    values = c("Lost", "Sunk"),
    replacement = "Failed"
  )

DeployTable_CCES

```


